ARG VLLM_BASE_IMAGE=vllm/vllm-openai
ARG VLLM_BASE_TAG=v0.17.0
FROM ${VLLM_BASE_IMAGE}:${VLLM_BASE_TAG}
ARG APP_DIR=/workspace/vllm-omni
WORKDIR ${APP_DIR}
COPY . .

# Install system dependencies
RUN apt-get update && \
    apt-get install -y espeak-ng ffmpeg git sox libsox-fmt-all jq && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN uv pip uninstall --system -y vllm || true

# Install vLLM from source at the selected commit using precompiled artifacts
ENV VLLM_PRECOMPILED_WHEEL_COMMIT=2754231ba3a72f41e62922d1552c33e8f3f6a9d1
RUN git clone https://github.com/vllm-project/vllm.git /workspace/vllm && \
    cd /workspace/vllm && \
    git checkout ${VLLM_PRECOMPILED_WHEEL_COMMIT} && \
    (uv pip uninstall --system -y vllm || true) && \
    VLLM_USE_PRECOMPILED=1 uv pip install --system -e . && \
    cd ${APP_DIR} && \
    uv pip install --system ".[dev]" && \
    uv pip install --system --upgrade \
        "flashinfer-cubin==0.6.6" \
        "nvidia-cublas-cu12==12.9.1.4" \
        "numpy==2.2.6"

RUN uv pip install --system --upgrade \
    "flashinfer-jit-cache==0.6.6" \
    --index-url https://flashinfer.ai/whl/cu129
RUN ln -sf /usr/bin/python3 /usr/bin/python

ENTRYPOINT []
